import fs from 'node:fs';
import path from 'node:path';
import process from 'node:process';

import dotenv from 'dotenv';

const projectRoot = process.cwd();
const envPath = path.join(projectRoot, '.env');
const outPath = path.join(projectRoot, 'src', 'environments', 'environment.generated.ts');

let parsed = {};
if (fs.existsSync(envPath)) {
  const result = dotenv.config({ path: envPath });
  if (result.error) {
    // eslint-disable-next-line no-console
    console.error(result.error);
    process.exitCode = 1;
  } else {
    parsed = result.parsed ?? {};
  }
}

const apiBaseUrl = parsed.API_BASE_URL ?? 'http://localhost:8000';
const googleClientId = parsed.GOOGLE_CLIENT_ID ?? '';

const content = `// AUTO-GENERATED by tools/generate-env.mjs. Do not edit by hand.
export const environment = {
  apiBaseUrl: ${JSON.stringify(apiBaseUrl)},
  googleClientId: ${JSON.stringify(googleClientId)}
} as const;
`;

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content, 'utf8');

// eslint-disable-next-line no-console
console.log(`Generated ${path.relative(projectRoot, outPath)} (API_BASE_URL=${apiBaseUrl})`);